input_data_modular:
  file1:
  file2:
  file3:


input_data_exploratory:
  file1:
  file2:
  file3:

output_data_modular:
  file1:
  file2:
  file3:

output_data_exploratory:
  file1:
  file2:
  file3: